name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_MODULE: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: python -m pytest -q

      - name: Streamlit smoke (start -> probe -> stop)
        run: |
          nohup python -m streamlit run ${APP_MODULE}.py --server.headless true --server.port 8501 >/dev/null 2>&1 &
          for i in {1..20}; do
            curl -fsS http://localhost:8501/ && echo "Up!" && break
            sleep 1
          done
          curl -fsS http://localhost:8501/ || (echo "Streamlit failed to start" && exit 1)
